name: simple-server-monitoring

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 * * * *"

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  REPO_SLACK_WEBHOOK : 'j){_-Xkbj%)^-d"^c2^a6-}bu4-[#!*-`t"?tiAlUxh3bj`.P<p.qBFo`_$@_/#wil>xq3;yn-6;-ku,O'  #optional env
jobs:
  server-monitoring:
    runs-on: ubuntu-latest
    name: server-monitoring using http request
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install node-fetch
      - name: Check request
        uses: jcy0308/simple-server-monitoring-action@1.0.0
        with:
          filename: "./urls.json"
          protocol: "https"
          slack: ${{ env.SLACK_WEBHOOK }}
          reposlack: ${{ env.REPO_SLACK_WEBHOOK }}
